---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption-key
  namespace: n8n
spec:
  encryptedData:
    key: AgC6hlJzMi22f1/ZIOUBLzmjc68ZbEjdgkYbMXtD4MjtctcdmLPgm1Cgxh36aTa8b9WAX9OCvIJgOojkJkJSmpr6IAhga8FncJxgkqPaeCJJuE2c6+Yg7YM6ndp7Z2oBiUHON7bQIet3PCzjGMRdOMp9jcopTNXd0WP466KViiiBOAR76aWu1KAGXaPcg6/fqOH4/omMw3sz9IbfURXWqhid6cIj7VRfXSBsLYwNHWLLvUbXKrl68fkd6kh/yrUB7noCiAamHu/nGb60FzTMzX94+G9OWF1RVACi+keZS4/2BuCUSCfHhOY5krSRp8RejnJfM3U0Cis+81Hb1h6mq/2SNqCTqbXyFT01rJ/i7GXO2ra9KCy3BbVQ99LhfdGWxWR1jpxVuCsruKkk+aCVKJfqtoRexyGMx3QO+CQA3UyCLtlGSCfV/sOWsBAaYhNXsTHAuJjAtMCFYo3qOW7/7OFagcwZN8iWo9a+bK9zhYigm4tkPGrUb/psVL1ZXZ5OYV5gM9VpMnp/3C+jr2T9Kz3jYHo1YbvqHaqLOueA1IcOUK58joN2MMqaCbxYS6d4IfWEXT+5vAxx3HK8CMDD6/0vFFqpmGU65TyflgZyNTSTFxBWyhMB6gP9twtVYsY5M6kEMsesNpCJVwbT2GNM7/K6hIjFq/uWsTO7dsXKVOl8kYCXgWwaTMmjTE6T5XG7H3JWHiQrg8o0M16T6WZg2WbcGG2c45+QjW05p5cEtJ+4toMLoq9Vgi6g
  template:
    metadata:
      name: n8n-encryption-key
      namespace: n8n
    type: Opaque
