---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption-key
  namespace: n8n
spec:
  encryptedData:
    key: AgDnKAi2t5yzeaJVgXEyDXh94Fw0zUqsAWXAVvogShFI3KqYSwf5RWHp3Aot9YcnmHvnL/cZB06wEL0kowsVas1DixIGjOFZqI34OQjxANqxJc5zfc6/qYaPk40b8B3WNTgPOvBpq0ETx8Lm8ze+RnNWHtm6Y6XQbFMkCyKyEsusDiR7NwwHWfqG/0UOl8eXZmHVGOURxql27alqYQubdVH+5xpAZ71GSBHBqDr0NjKm1sU3SVwq8D9Zfxt9CJPaCDobnoIC2uMW9Y2Nrr5ZLEnMbvSKvoCVTSuVStOf9Lv20Hmxa9uLRgmEV3xR/c3hSw6XFsFzyNOzoxrAnIANlVA8wg3deLiGOKBx3qZqgdVab9FX2gs721dSzdntcGXAMK4ZD3lBDAFnU6SISP2JOdnKU1fjSmdJpzPslPhz5NGIs4lr5XiOIclxGRs3i3kB7BWbAW0zwt2+ybmeZoKVepLKQmkki0TObwVkafULySk6HRxjzXYLiOaxQQAaIuZNgbmAXGJ8ybw2WYNlMnQrTa168mCB+C8Vyb1aYSqZ4XupAJKgbUUN6X/lN3yTwfjOzRqgZ5GCrDzEdYDGua8wb3lNHt6qcDnX77Oeku4Sguz7tnHXOMmsgQFh1z0oyGwg9unU9V5P5Z59Y0lF2TCp3UyrEA0DeQNbBv6n2Dre0Cm6oJd5uL+unVNXMaBQtcKnRBuzAxp3GxUqWXqIQjbE61PTogedLu7Nm+jRQ56OJ3FZPQ==
  template:
    metadata:
      name: n8n-encryption-key
      namespace: n8n
    type: Opaque
