---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-secret
  namespace: n8n
spec:
  encryptedData:
    password: AgCzrtsaCgmU3UHXhTFUVFNifwy9GMmljcd61zdr2zmGX8eBx0KLP9RfI4yRuRdJCig91jIHclLnmkVzJrEqhK/s8lp/XY4+sOgfVY6ZmZQt8rnGhtNR4f35gGTk/ZwHURORh3NJ/HqlWpFxjIVMSTxft4O/bz/PKc1OY+xTbeHdtXH+rk+puQ7Znsms6KXN2x7GwdfX+dqyleNxFnP72NU6HqKUAfWzSRc/fZ9ar6qHxd+b53aSsB4JUyqOTL3ZLPq3D7QEws+CeuQz7dhQDe4GECTSxZBU7fgjqgSUy62pkatdkNb1m7jvDZHs3ZLhfiKpknunDsIH96SIKcPb10ahgef4AU9XppntUJINeDSLpSWfaYVI4ctWTcomWRdikd7HFEqBk+36bt2g/4u5kMkWAYi2fixIGt+R6FRs3j1fzQk6T1UNDuwv0GRZ9m4GndntLdEdjPe6EMQFSCXNu4/VV+x+4TyIVe1nI12zi6HYftRWXJbITB6tYsrlf54u4055/+A2vptKLaLQsuEv8rNrtUF7j/Wf0V89I8RsmWRx+CMPLiWSHIefZMFmNXQsdvNTta/FIdsq6HY6g9m7UbcobND03g6ZLpoTa0G9O/Pynz4V4O4lWADXu/cDECa0AzQRZBR0cF3OcxU7EFOutWIVeZdZ3RD1oPcCIPeCB2DnPAygXZ4Iji/XWnvM1wts4zFNWzX49rh03mEjrYSzg8wpu4hKL9vD03FpvMWjQMg=
    username: AgAwBOBAUqW8nANLqz2UOFL0RXbgBEUl2klpvb0bB4TsIlEkcttGzkRxQR6R5ytGXoLIU9oHr3Y5koqqgZMUTu8pKOKPm3VhlfGcNrT4lqQhKKtfNFigGSfLIsF/i7jUBgIdXFRrA0jiALY1q2WtjlCDcj61U/7Jwc9MSeyqfrusR2zqNBNn2Iv+/0CwUZilFq2VVSFeD7hjaARdnc/gkZ+LzIrr9Z3ONrLLOD1xmLoJDLL7EtETkwNSjd2cNVNdARtdSSsqJv04ClwPNptAxkALh4jY8/CZcrruXNP7qt+yE233s/6B4JlE5RgGCa98v5XhvhHrRTcwThbNFlXVkHhqMIV57dUPKSkdjd2s3dLwJvFOWany03o2jbF28JQvv+mOhJCN3R453Z3CIpKqa3Zj3bDpZDOvCx+4po2bK1jF43+xCb8C2mzEh9+b7tvklHGXC89E7hnU6Tb1iA5k9stCcoPDbBY/GnIZYaKLJ3X0BzJQ/dn8tglEY7UXlK2/Omkd3I1LP9jNTDNDKAl+1v5hM1JVAR08V+dPFOpduMCa/hp4DHhpJyPal6cp8+VsCaFuwmZjJpKkJQFcgMFwbGkJo/ptuKNkhaJNHx9uHlJP/H2lJbO5aoyfIVcriblOItILWv6OEg68m1kEVAoh2jmfgg+HMeg+LI238YIbcQE31oUlVyJP/SYbwn9qBgHrZHzxwZM=
  template:
    metadata:
      name: pg-secret
      namespace: n8n
    type: kubernetes.io/basic-auth
