---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secrets
  namespace: ghost
spec:
  encryptedData:
    mysql-password: AgC2Mf2v4OmRGLeIhJVHLMqvx70VqiHnQ4Lynm68etw9w4ffkrt1KBNeC+0vP3t5L075fOAr6I77hhNqWRlLCmWbiNjg0ODYvmwBpwqNsfSgh41h+aSTsLQH9AELAemJ69jEB7gMFW2imsECP6QIu0kUQABc7N6kGgdiIHo2edtRmdcfJNyhq0A0MhV6taAK4kIU70a1JHP1Et84/bYeV/Hwo4MLvEuyPrxjuIcUZ40aOaFfcuNVUnwhbJS2AGl873wuGFQxUnzzWKShhJ4apob97s/UCSD5DmL28aET28cNJfsENqseZXKdf2k2tSHJLaUE3kxAtExfkWvUqeJXHhS8ICdWyEZKFV3PzFnSsYD70cg9oNRkJI2KwhIGOze6k88IdnqnRNwMc6L65aKYKC8tOU+pEOOpTmtrQYynJtj09a1rsND1RsRRQ9HPEUVlE42aVY8lyOT9jHfyfy2h+YUYKrIIe6uLuDRmMqalNUFRmRaiYIiC/YtfqV0R1ISsVcDEZVVwdusgy5jU4fR9bNmD109k/KwqltkflHh+Hj0MzO8gyWX7Cdxk9sY2ALgE2Eo8hIcgXAWB7odHjqp5QSx+vLP8W0YMomK3uYK+8XBR6cwOYqaohodr1EoaLa6qA6O7Q1I36WdWuPKyH/X+6fhRceq3vgQsYajsGF6oKc5piZYWSqoG70Gw3FoNXVktMnFei5qb+zUwmV8hru3K4Xk=
    mysql-root-password: AgAjxYqKoGbGT72ZZ9pZ9YvFPNIlJ09LtDSPyDp6JfaIgbJG3BuEfHZMQtHinZRL0lBp+Gzx22T4orqoC7UpSsB1HVvhP5JqcRmLJekrWEQjCnlG35S8eUMfOT4W3wlTbswg2YoXMyJdtLQFIfMle6HEZ4DAxgASIQxK91DTsJRm7r7Xudfq7fwyZNiJoRgYvINcLUTo2x7NLUCqgmZ0CL1XSqVPCRlVpBmMF0fNJfQJJ/IA4i0CLU/t8fPtSgdVqGeuD5I/4185GxlvQPd2XrUop3GiNaZltXaftM+ELsbGGc90mBjSTAn5fVI2iyzDHsym9opPXKHA6od4FWktiFGLt5OFYbgeF45ESdjEbejDuhFN+m/XJn9J5SZNUdxIS2VF2FMDI/UcRWO4bjNjDnXfl934W23JOur5WOypQdh4sOx/K35mvBkUeGm7lQ7WlfCcqpJBT7YDWuCl8A4xFIMws2h/wQr/jbR+FyKyasCHzDVFLYymY1EfQq879QCz56pw7DTCL+RK4ZbNklrsD4TwuuVZO4K0qGcihQUQtV/ffM/tQ0PZ4SqcWkRIYCq+Es5vDJnU8j1HzO80VfKBdhI1/NTmFVvuEmRBOFXly9yVlzudPQ/pKEaPm1wQmrqOSRA48ogSK5CGwydFKdVweGlN2Wr9VHwpcJxlPRl+xP/jtsTmc/MtOcyzQI2Fyfzx81nNkHju4IclPwd0/Jxk7PM=
  template:
    metadata:
      creationTimestamp: null
      name: mysql-secrets
      namespace: ghost
    type: Opaque
