apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: ai-trader
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "lutergs",
          "password": "YOUR_GITHUB_TOKEN",
          "auth": ""
        }
      }
    }