---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: ai-trader
spec:
  encryptedData:
    .dockerconfigjson: AgDHHOSDXJsjMA3UBFAcJgDZiYjq5GNue2EgxtQRnMz9wBzEVACegTngE6u4/vlA5p0Q/X4457H3hZW63g6s5dIry20vIF0xU+6MY/3q4apFXx84yUpS5/qAmnQMIQdHplqgdLkzhI9DQwqKs1W2qz6SMu5PUsp4zja2Cu7kABZfXitxVkCjLVzVXvKPt+U72kKlFNxTeWhnuA47U63h0iS2Ad173yyiNs9PeO9xihvMsCh9B3YLNNI70hcCInfenLZKwd/uMONh06U/IADNvTkPl7eg/YAlgwP6Hsovte4c6+gLL1tbGMzWli/SkHchRfbP8S5dp5rAyG7MxgzsraGI/aIP7juZwmV3gkOSfZMNhZGprCBRgRzdQhdO5h+2OdRC6H4sz/VpiBCSgcZpDKEGYGJezxjvshQP+cmOJy5QSPO5iVJZPiU8gh98tYqExtggwH51wN8n1Q4fK+9CMyV2cdt4R/iTr9UK6Mi/h1YihZ2agZHZt7LDddoqOiI0Wqk656VulW7Ems5xVHId/2aRBt+Tku5zrRiIPp9EV0MtBXr4QkXC7A+s2Bys45GL8qJ15YpChzfkx00ks+jO0vO2HhrSU1VExFkgxESw/s4wZWv2cRFQwNx7x0A2xYDsOmn6NE4YvYNu2oX49kvWpVPgUSqlKbFRQZEP6+KlBL0fywFKTlJv4pAInvKA8fpo+Z+GveN411odSyE3/asbU73RkEmledY+fl71R8B9rEcSoWxL33soIvg9/GWuRvD1sH+t+KR2el0eum+NJhJ90CXeV3pdVjagQHYdu3yifYjPNR8enlA28RS+hyuOFvCyZ4phsNPzxZqrwKWk6M+X3SGitm/KmPw24/V/TxmUv/gkMNflXZf8qjBB6pF/q4OGXtqU/cNma48miQ==
  template:
    metadata:
      name: ghcr-secret
      namespace: ai-trader
    type: kubernetes.io/dockerconfigjson
