# need to set external IP manually in service to work

apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: nginx-gateway
spec:
  gatewayClassName: nginx
  listeners:
    - name: ghost-blog-listener
      hostname: "blog.lutergs.dev"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: lutergs-https-tls
      allowedRoutes:
        namespaces:
          from: All
    - name: ghost-blog-admin-listener
      hostname: "blog-admin.lutergs.dev"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: lutergs-https-tls
      allowedRoutes:
        namespaces:
          from: All
    - name: authentik-listener
      hostname: "authentik.lutergs.dev"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: lutergs-authentik-https-tls
      allowedRoutes:
        namespaces:
          from: All
    - name: argocd-listener
      hostname: "argocd.lutergs.dev"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: lutergs-https-tls
      allowedRoutes:
        namespaces:
          from: All
    - name: longhorn-listener
      hostname: "longhorn.lutergs.dev"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: lutergs-https-tls
      allowedRoutes:
        namespaces:
          from: All
    - name: home-assistant-proxy-listener
      hostname: "home-assistant.lutergs.dev"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: lutergs-https-tls
      allowedRoutes:
        namespaces:
          from: All
    - name: n8n-listener
      hostname: "n8n.lutergs.dev"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: lutergs-n8n-https-tls
      allowedRoutes:
        namespaces:
          from: All
    - name: ai-trader-listener
      hostname: "trader.lutergs.dev"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: lutergs-ai-trader-https-tls
      allowedRoutes:
        namespaces:
          from: All
