# helm upgrade --install reflector oci://ghcr.io/emberstack/helm-charts/reflector


apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
  namespace: reflector
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://emberstack.github.io/helm-charts
    chart: reflector
    targetRevision: v1.0.6
    helm:
      values: |

  destination:
    server: https://kubernetes.default.svc
    namespace: reflector
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
