apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ghost.fullname" . }}
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ghost.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ghost.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "ghost.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: production
            - name: url
              value: {{ .Values.url.default }}
            - name: admin__url
              value: {{ .Values.url.admin }}
            - name: mail__transport
              value: "SMTP"
            - name: mail__options__host
              valueFrom:
                secretKeyRef:
                  name: mail-secrets
                  key: server-name
            - name: mail__options__port
              value: "465"
            - name: mail__options__service
              value: "SES"
            - name: mail__options__auth__user
              valueFrom:
                secretKeyRef:
                  name: mail-secrets
                  key: smtp-username
            - name: mail__options__auth_pass
              valueFrom:
                secretKeyRef:
                  name: mail-secrets
                  key: smtp-password
            - name: database__connection__host
              value: ghost-mysql.ghost.svc.cluster.local
            - name: database__connection__port
              value: "3306"
            - name: database__connection__user
              value: "ghost"
            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-password
            - name: database__connection__database
              value: "ghost_db"
            - name: data
          ports:
            - containerPort: 2368
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /var/lib/ghost/content
              name: ghost-content
      volumes:
        - name: ghost-content
          persistentVolumeClaim:
            claimName: ghost-content-pvc
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
