apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ente-photo.name" . }}-apps-url-secret
type: Opaque
stringData:
  PUBLIC_ALBUM_URL: "{{ .Values.url.publicAlbums }}"
  CAST_URL: "{{ .Values.url.cast }}"
  ACCOUNT_URL: "{{ .Values.url.accounts }}"
  AUTH_URL: "{{ .Values.url.auth }}"
