apiVersion: v1
kind: Service
metadata:
  name: {{ include "ente-photo.fullname" . }}-service
  labels:
    {{- include "ente-photo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: api
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    {{- include "ente-photo.selectorLabels" . | nindent 4 }}
