apiVersion: v1
kind: Service
metadata:
  name: {{ include "ente-photo.fullname" . }}-service
  labels:
    {{- include "ente-photo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ente-photo.selectorLabels" . | nindent 4 }}
