apiVersion: v1
kind: Secret
metadata:
  name: museum-key-jwt-secret
  namespace: ente
type: Opaque
stringData:
  # fill out values via execute `go run tools/gen-random-keys/main.go` in ente museum.
  # key.encryption is key-encryption, key.hash is key-hash, jwt.secret is jwt-secret.
  key-encryption: "raw-value"
  key-hash: "raw-value"
  jwt-secret: "raw-value"
