---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-secret
  namespace: ente
spec:
  encryptedData:
    postgres-password: AgAM8523RkGF2alaZMRBfELnByY2ZQSVXqZ2pG4IuMPVYn1SHE1unq1xR1Gs0FR+u+4rp1Nzx7MlXVgyzg5TbI0WTijwzpMvZgCG8DMjBmHtUParXBCw1uIZ29KdQetDxm2Q6ZJrunuExLfcvrAKXfQkWarr/6+Ln25Tzx10DoBqXvZx2+9TZgA6sb7azT9+9slXlVR59GT+vzhOmyjcTZ82xOkh9QrAL4tm7iZmTZI+QK+EN02O9Sf6moyN4xMYct+v021L01QIZzDUiK9Ruxn8IXfoatP2CM5D1+kmFprlEdbBIXvxJNLVlxbftURVUc6nu5vcIkhaFBw1XQ4ywKA8n1TGJX6P8oBB/rUlJMlVdtcQn/bJWboaf91wmkdkaDKpRBq2JSNy8zHMgZ0Eunr1Te0fR0VEs0tx/GCwbUjBlMUXE/qXINYFAp++1RvzlAqFpAcZkgrorMIjbhIg/R0acVBBSBgI1stqjQHciZDYHhqWsRnP1LBR7c1yWCXLSxIZflov3k8Lv+JuADcnpwOredpfR/1jJ3cko7vXZJea+MnVmKNl02qrtdgFVGJnO8oGjFAShzJFaYoajg6aA56Kw/cb14GCPU/IZzci51yrWJHyMKyTUJMibHN3b9n5AF3ocAyqhaPanWiRqinTLRHs/pIvt1Xt5wFI96ixGo0nB5jUSRuBceWPZSTobOSfDN7yffAOj/ZuTn9nNgKi+Q==
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-secret
      namespace: ente
    type: Opaque
