apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: ente
type: Opaque
stringData:
  aws-access-key: "AWS_ACCESS_KEY"
  aws-access-secret: "AWS_ACCESS_SECRET"
  aws-s3-endpoint: "AWS_S3_ENDPOINT"
  aws-s3-region: "AWS_S3_REGION"
  aws-s3-bucket: "AWS_S3_BUCKET"
