---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pg-secret
  namespace: authentik
spec:
  encryptedData:
    password: AgCHDQdimIwDxl22TVuxmv+s3bXSe+dQMXgZejqrjoK3ycUPpkp6JXRnkDPs8wSiNdqW8G8FGJ4DdlMnbQerwebV6MIEQdowvNOQcPFTVCGhfGcfMnyJCb3aJdqMTQWfGsdIGJ7lacOllKbciSkkEGJ7gxYdnHcRO+qxqnw58vIgUqR08Dx3kdaIcBWGpCv6qqrspJAYXJfLiqVpF5BNX1jnw4s0lQncagN0JHcbJ5oRMyKBRKpDhmWuJZzWKxFdBAk4LipJOMvb65GQtGp0flz7Jc2Kg6N8TCXOJ1sNejUvE/DnV7Z0/qHVxMhX40ftrwR+BqBb4yaM21S56Tu0WLiSW+ZyrtA6wBLftVYfxritNfKXOTn/mwwCK5HqFXSGXf92NqcPWgtEoRLwu/aXVi5oSUU4ldwZw1GuR9zeB+kTix3rY/hN7ePFvfDZVVX0dhR2FhbBs/V1mO7RFg1/r70XAaeV4BxoKn5ffuQMB9lkp9rpPhZf+rNhPe3kTVVu3lz8LSMMfH+w6uGjsu53JbJH1ZuLEXwReMP5UD4o2gAM6jlWA5SXrlBxCPgZguKZqWafgLpCwu7GQSpC5RlkSrSgR0/G1IREKnqQUfJxT7S0gHLiQXNLwXQatSaJfwqINE07yHIzTEDDKrA7JMHvEuUBjjS4rVsqsYEt0Ag7IQyL6YAEaqMGfY2NlBI5ydQAr3zNRAFR9Nft7lO3iHRqP7Mhs3M=
    username: AgCWw6UhiPWvMTjkLbs1H/eV9+qv8R+xgjlZ0G/8bPaeoOkIanW2uAOOy8aceyiaJEDV/amuFtcK7LoRnS9EDglm4COH5y2s7t0gvpAEkVIQhZQistsoDE0vvilAm3wZVDoc0lTngdIIjoEGy4t5qwe4LWbn1PYK6m8j/Hk0KPH2EzgjBGiWxoSzk3cJysJfa+2MDpcpJNqGHfbUbhmgIusE+isPy2+erLI7spqr3MxHZc5BkAAOqKwWDnTD0gl0g6bGuhSVsD9UoG3JjnbQ8UTr4xdRau+IShiaVuTcFk3veQFJvlZ3HOWVKBdGtAZI0nUBoPsSTxQVjmSfgYdI25DKy/7lAbH6qj0LWg5e4PApo/C0r3qsLef+FXe+IY692l4cSLI8s/gZD8Wi1zYS3XUaDEx8Ysv0LMMisgaEO6CEYbYt2VJWbTID5moR0MexUjT3P+Z7SftSJcMDMATvHUh5ibdBHtT/DvkFUwoQZuWWHIwH/OB+pUcpG60N+kj/bj2Hw3V5HfqODRiQ+HOF8ZYL7XlPo3vKkxufMWp00zyDXNwi72YJcjYxbigTrdnWp5W3Xn/XRt05lPqr8UX207vUOsugs4dikWcvpu1/601R/fxxLYdZHpuQxKm27doS1HyzXVfbg1ZjS+YkSlv7xsQyjPOTP4lJZz6FaREnILyuwDIgq1MBHJFsqYwR5/FEZ1G+jPUzKwRJf1A=
  template:
    metadata:
      creationTimestamp: null
      name: pg-secret
      namespace: authentik
    type: kubernetes.io/basic-auth
