---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pg-secret
  namespace: authentik
spec:
  encryptedData:
    password: AgB4XSwJR3ddqXy1PPdfkUCZ/u9tA8eBeOf1IQvOfrmGqbjqx7gJKuxrfYfIsBnRL5fUEHGGVPfSnHAa6ZoSh1SIj7V7WpmrOerf/6tesIRQ0TsV7HDNQz7C2TwOjcrteC8/4oYfqpfRcnPXqTQ5ZQB3sYs9EkoRjznISqjTswhei//JInPgYfd1Anl2K0kufKa9gjUHlNFD9URIN951w2qG6dKQiQ+nkwRh3kwCq72T/s8a8g92NynajWkf+EoE+du+LtIYMZwr2Echab+qr7ouXjY64punKZ37MQJ0T0pxwirazzXt62zQNX4FqJdR3ylz5fE3OHUvC8PkamOuBHTPfZjXrTXZ9Ys5gKOzkcaB1t1BnIUKcQvFTVwuoPB9LmFi9K96QwjdV46CmlP83jwrAJPpaw/vYM84zu3ZgE4YzOjdqxTNRxbXyuqa6jhpKneO/JJe/tKCgrrP5ORGDQH5GBzd9jQvA4IXt4d8wIZk9ijCOuM0hDO0SAdXFHz37MZiu2/+3H8eqzvi7khghAwcUzJknuUe7hCiotLXYlGFL+mbmf5+WrZddiYOYWCxts5cMlfYwFeY24x5TnyRaNa9AysJbo8ECXBc+w++zlXcs0cGhCMOcgAlXwuvQAwlISmLWIoIl7PNTSHpGiSbqg3nTuNXz9P8XrHvcKYjpoALC9SPVZMFZcLXJeG4pJ9Dw6P0Zbx7YjaOKC07XkbjHNFx73E=
    username: AgCzUPAcnE0qyQR/RsHOAKp56EuH2bLOMCdOY2SN9k4Xr2H6QtVbUYCcaNWR0F/K8bSQ26mSsWjB4BQJrPOSUzSOMXaBbhBbwwwB9KCLxIQm1HyAoBvnxIcPsZl3htoIT3TCMMegyx7M26J9CzhuH2xPE9B9b1iE2qJ0EESsii/gghqhJWcDFGxqUW6Tz91nVBw3buscVeZbQVyod6Z9qvXVcG09HOHwX75X0wfxg5OGtTKPVww7Pkwzz1tHcp7cCltDHIXXie5LMfpdYBk0kTJGzVHCnTeanlOTWB/CsyXq1WEeY0sQZjPUpmg1v3TCNmTt6hFFGnvxo0SyYbbd0iumyRH+6pKkF4e1rLfxcmyo4YFixJMNiHWJvsVsPqCa1/uF5m0eXTuzbeRFrLqJ0kJ6l0XcNydeYNJLUdZAxssMVRmn1dae+IuqkMDapSpTwFUbWq4jlIBPpAKiVfmlFSFIuU5gChgLAc6GRD0IIZBaDAOCgvaZwju0SP8Cs0PQmy4BYGbIWYML1G4guPzWV675HnJz3k60zIT3nT8aJlKi7nvbpscEy5k4rzXyp+zNjdPQ6hiblw+CcSfeTeYALLIR00nBfQwalW8naKMviA8k95+SHW/5/IZ6oZe/plcpx/bCV0xu5Bgwx8COnVgV0DiUYZnujsdUyMay7ft+NK2EO/eVMNS3xqClAAKw8VwqfCijXDwRxws=
  template:
    metadata:
      creationTimestamp: null
      name: pg-secret
      namespace: authentik
    type: kubernetes.io/basic-auth
