# Default values for ghost.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


replicaCount: 1

url:
  default: "https://blog.lutergs.dev"
  admin: "https://blog-admin.lutergs.dev"

image:
  repository: ghost
  pullPolicy: IfNotPresent
  tag: "5.117.0"   # 2025.04.20 version

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

resources:
  requests:
    cpu: 0.4
    memory: 1000Mi

webapp:
  replicaCount: 1

nodeSelector: {}

tolerations: []

affinity: {}
