apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: oci://registry-1.docker.io/bitnamicharts/postgresql
    chart: postgresql
    targetRevision: 16.6.3
    helm:
      values: |
        global:
          defaultStorageClass: longhorn
          postgresql:
            auth:
              existingSecret: postgresql-secret

        primary:
          persistence:
            enabled: true
            size: 30Gi
            storageClass: longhorn

  destination:
    server: https://kubernetes.default.svc
    namespace: ente
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
