---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secrets
  namespace: ghost
spec:
  encryptedData:
    mysql-password: AgAMT1q86TdlViAGhyzOhGjVzW3KljwdcxQkOrQPWTWkTJe1rnjP0vEvI7dJYdJQzI3n/B+XBlcs8UDJLq+6G18Sft/2da1esFMVNPgI5RaC1ljqF0VD0IpGP0ojmiWioBjxyXcOhFpi4zm+ICLlrwB8/21DZGFb2nlL5e+Hlo75fp9hMpg/TbPPJfyhcNT7IdoMXxZ5wjqtT/LRUfsxFTONci30yqhYQY8x0eCvmFyNu2ATuE0RGCqMFRloYJRZMzpUtRwRtUPgMvLY05YxF02yFxDh4KlTwo/l0rmPDAqTLIE1pHr8W8dmKFOBjX7T86QxXYpgUIZ9OrYfvlZUo7w+k2I8gZ/8k0+CbnHRvKtvPfqJP2l4AucBPH1becrm8ErMjAfX6f8cdGlGDsXTZ6oq7cu9ttkP6zKW9NY38gOqB+ajXJ6OTwcMAUL8/YtutxpbGVGVuj0GxXuLmx3shsqHfA4lMoOsMC5EpSP+m537QUI4ogPvJp2rcSQN6Ib7U1KBJf1+QFfL1M8fafp4tRTJk71Mb2bc70Wr0Go5hxU+jo4ZDaU80zZ6RROezRStST15qqgpTlno+BXT4pLAam1I0l5V3KxaBy1BbeQsbu0nUqyoDzBdZTE62xLpt/J6csj1hcPDIiSV5R6iMFeG6W3fwkEzd7QS4qYqlP3/FT3nm7Mk839x7AerWKkYCUVZ+9gCkJL8n2L3XPa/kQ0j82w=
    mysql-root-password: AgCPPPyylMc/8AFFTpxnaWmqWdigL4YbJ+TagFxyvEy3Snr0ra9f7ihD16AKB96zpOjWCWL/uaSHi1/jqPaKWKG+T2ZqDQGpyy8u6Y64KX+9y10UJDt50BF7KxXC/qwYWDx/uxUZNgZXmbIkd+4Yh0P+CPhaUOy6EzJsGB/BRC6/a++dD48/w3EoPeaKaId4YaHUyuMQtn7DNbJT13JVARIPWIuRvGDULXeZFSTIQXI5FaywCAk0h1lNVvfOdkZp/sxZ4OmI0IfDe77/AU4yMGUrhFkARAfeJYVIttvvC6cnEUn1jqDQqSNZVV3GdwOp7oV1py6qV3ymLvJ+6Olv4LhUmX8OdpCnUVPSrAObJle+lS3jniI5p47H1w3T4uBho+GnO3tjwjwhbXYqKUiBSI4d7L7El+7nny+OPIwdum9ICh8uQNbabBQAE5z36FmRiOkJ181ncfFGBjxuUGblR1cSdGCUJ/rXxtAUrGwXg2Uvuqae/oDnfg/T98Cow7NsFNoPLnWh3WS3F4E8A/g5fH+WtDtkIdEL5Gq00uRxYuWUKrYW92RWwsqDd6hF0gRXi5ptq3VHT1jXsUQLQ0ZFng6DShJ4FGsEwCsT07G45q6qugqdTRa/7uQ2vy8QIBbpnX+sqyxGONumrXqyFPfMm990cmZZlBU8vKB/Ez+BLPqFvQyH+U1UYO0umyUjfOoZg/+a9sTSwu4hjoWQi66XlK8=
  template:
    metadata:
      creationTimestamp: null
      name: mysql-secret
      namespace: ghost
    type: Opaque
