apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ente-photo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/lutergs-dev/infra-v2
    path: argocd/helm/ente-photo
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: ente
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true