apiVersion: v1
kind: Service
metadata:
  name: {{ include "local-proxy.fullname" . }}
  labels:
    {{- include "local-proxy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "local-proxy.selectorLabels" . | nindent 4 }}
