apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lutergs-https-cert
  namespace: cert-manager
spec:
  secretName: lutergs-https-tls
  dnsNames:
    - photo.lutergs.dev
    - ente.lutergs.dev
    - ente-photos.lutergs.dev
    - ente-accounts.lutergs.dev
    - ente-auth.lutergs.dev
    - ente-cast.lutergs.dev
    - ente-albums.lutergs.dev
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
    group: cert-manager.io