apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lutergs-mox-https-cert
  namespace: nginx-gateway
spec:
  secretName: lutergs-authentik-https-tls
  dnsNames:
    - authentik.lutergs.dev
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "mox"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "mox"
